### ISSUE TITLE
Github Action Fails with ImportError from 'click'

### ISSUE THREAD

**Issue by stumpylog** [psf/black#2964]
**Describe the bug**

The Github Action step:

```
- name: Run black
  uses: psf/black@stable
  with:
     options: "--check --diff"
      version: "22.1.0"
```

fails with the following trackeback:

```
Traceback (most recent call last):
  File "/home/runner/work/_actions/psf/black/stable/.black-env/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "src/black/__init__.py", line 1423, in patched_main
  File "src/black/__init__.py", line 1[40](https://github.com/stumpylog/paperless-ngx/runs/5724998040?check_suite_focus=true#step:7:40)9, in patch_click
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/work/_actions/psf/black/stable/.black-env/lib/python3.8/site-packages/click/__init__.py)
```

**To Reproduce**

Run the `black` action on a Github runner, configured as above.

**Expected behavior**

The action should only fail if files are not formatted.

**Environment**

OS: `runs-on: ubuntu-20.04`
Version: `22.1.0`
Action: `@stable`
Python version: `3.8` I believe

**Additional context**

**Comment by liranbg** [comment]
@stumpylog 
try with locking `click` to `click==8.0.1`

**Comment by bradleyhurley** [comment]
I just came here to open a very similar issue. 

The issue is caused by the release of click 8.1.0. 

Install `click==8.0.4`

**Comment by ichard26** [comment]
Oh wow, Click 8.1.0 drops support for Python 3.6. We will have to either drop 3.6 soon or pin Click up to 8.0.4.

**Comment by scasagrande** [comment]
For those that are running `black` via `pre-commit`, you can pin `click` to `8.0.4` via the following:

```yaml
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
```

**Comment by JelleZijlstra** [comment]
We should probably pin to <8.1.0 for now. I can help get a release out later today to do that.

**Comment by mjpieters** [comment]
The import doesn't raise `ModuleNotFoundError`, only a plain `ImportError`, because `from click import _unicodefun` is used.

The code would need to be changed to `import click._unicodefun` (and `import click.core`) or catch the correct exception.

**Comment by davidism** [comment]
Well good news at least, that whole patch isn't needed anymore, since Click itself is now at the same point of not raising locale encoding errors. :smile:

**Comment by ProGamerGov** [comment]
This causing black to fail when run on Google Colab right now as well.

**Comment by JelleZijlstra** [comment]
We do still need the patch. On Python 3.6 + Click 8.0.4 + LANG=C, Click aborts with `RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.`

I posted #2966 to make the patch more robust. Thanks to @mjpieters above for noticing that `ModuleNotFoundError` is the wrong exception to catch.

**Comment by ichard26** [comment]
> Oh wow, Click 8.1.0 drops support for Python 3.6. We will have to either drop 3.6 soon or pin Click up to 8.0.4.

This is wrong, if we still support Click 8.0.0 until 8.0.4, as long as the python_requires metadata is right pip will install the older acceptable click keeping everything working. Take this as a lesson to not jump to conclusion in stressful situations :)

**Comment by JelleZijlstra** [comment]
We just released Black 22.3.0 with the fix. Sorry for the disruption everyone!

(There are no compiled wheels with the release yet, we'll upload those shortly.)

**Comment by ichard26** [comment]
Mypyc compiled wheels are now also available :rocket: 
![image](https://user-images.githubusercontent.com/63936253/160485802-3bb743e0-b1d4-4ee9-a90c-0cd996d8f4e3.png)

**Comment by UnderratedNorf** [comment]
How can I fix my failing gitlab pipeline that uses pre-commit ? I'm not sure how to pin Click version in the gitlab yaml file.

**Comment by ichard26** [comment]
@UnderratedNorf either update black to 22.3.0 (remember thanks the stability policy, formatting shouldn't change at all) [or follow the advice of this comment](https://github.com/psf/black/issues/2964#issuecomment-1080974737).

**Comment by Edwardx89** [comment]
Is it me or does 22.3.0 still did not fix it? 
Using black==22.3.0 with click==8.1.0

<img width="863" alt="image" src="https://user-images.githubusercontent.com/20568113/160493608-de210ff1-8ebc-499f-99be-a41bd2c20ab2.png">

**Comment by Edwardx89** [comment]
@JelleZijlstra @scasagrande  
<img width="953" alt="image" src="https://user-images.githubusercontent.com/20568113/160494327-accec69b-50b7-4bc1-8efc-15eb3207738b.png">

**Comment by JelleZijlstra** [comment]
You're running an ancient version from back when the whole thing was in `black.py`.

**Comment by scasagrande** [comment]
@Edwardx89 you are running `pip freeze` on your `pipeapp` venv, but `black` is installed and running under your isolated `pre-commit` venv

You are not running the version you think you are

**Comment by Edwardx89** [comment]
@scasagrande Ahhh you are right!!! Sorry! It does work :)

**Comment by vhosakot** [comment]
can confirm this issue is fixed in black `22.3.0`.

**Comment by siaccarino** [comment]
It is still not working:
```
pip list
black               22.3.0   
click               8.1.0    

...
black....................................................................Failed
- hook id: black
- exit code: 1
```
Traceback (most recent call last):
  File "/home/ebsym/.cache/pre-commit/repomlzam_dy/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/ebsym/.cache/pre-commit/repomlzam_dy/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1282, in patched_main
    patch_click()
  File "/home/ebsym/.cache/pre-commit/repomlzam_dy/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1268, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/ebsym/.cache/pre-commit/repomlzam_dy/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
```

**Comment by mjpieters** [comment]
> It is still not working:
> 
> ```
> pip list
> black               22.3.0   
> click               8.1.0    
> 
> ...
> black....................................................................Failed
> - hook id: black
> - exit code: 1
> ```

pip list doesn’t tell you anything about what version pre-commit uses, because pre-commit has their own virtualenvs for hooks and sets the version from your hook configuration. Edit your .pre-commit-config.yaml file instead.

**Comment by AqeelAT** [comment]
Github action still fails.
I tried:
```
      - name: Black Format Check
        uses: psf/black@22.3.0
        with:
          options: "--check"
          version: "21.10b0"
```
and 
```
      - name: Black Format Check
        uses: psf/black@21.10b0
        with:
          options: "--check"
          version: "21.10b0"
```
And none of them worked. They all give the same `ImportError`. I think it could be a caching issue. Any tips on how to solve it?

**Comment by laymonage** [comment]
> And none of them worked. They all give the same `ImportError`. I think it could be a caching issue. Any tips on how to solve it?

@AqeelAT You forgot to change this line:

```
version: "21.10b0"
```

**Comment by AqeelAT** [comment]
> > And none of them worked. They all give the same `ImportError`. I think it could be a caching issue. Any tips on how to solve it?
> 
> @AqeelAT You forgot to change this line:
> 
> ```
> version: "21.10b0"
> ```

https://black.readthedocs.io/en/stable/integrations/github_actions.html#:~:text=Note%20that%20the%20action%E2%80%99s%20version%20you%20select%20is%20independent%20of%20the%20version%20of%20Black%20the%20action%20will%20use.

**Comment by angel-langdon** [comment]
# Upgrade `black` in .pre-commit-config.yaml

## Cleaner solution

```yaml
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      name: "Format code (black)"

```

**Comment by ehontoria** [comment]
Hi folks, just looking for an explicit answer here about whether or not this fix will be released for versions earlier than `22.3.0`? Or is the expectation that all previous versions of black will need a `click` version pin forever?

**Comment by angel-langdon** [comment]
> Hi folks, just looking for an explicit answer here about whether or not this fix will be released for versions earlier than `22.3.0`? Or is the expectation that all previous versions of black will need a `click` version pin forever?

@ehontoria  This bug is fixed in  `black==22.3.0` you should update it

**Comment by JelleZijlstra** [comment]
@ehontoria we don't provide bugfixes for old releases. You need to either update to 22.3.0 or pin Click 8.1.0 (as @angel-langdon already said).

Note that thanks to our stability policy (https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy), upgrading from 22.1.0 should not cause any formatting changes.

**Comment by clarabez** [comment]
When running locally, after updating versions, try following commands:

```
pre-commit clean
pre-commit autoupdate
pre-commit run --all
```

**Comment by alexcoca** [comment]
This still does not work for me. Any idea why? I am still getting the error despite pinning the version.

**Comment by iboates** [comment]
Not working for me on Python 3.8.6

pre-commit        2.17.0
black             22.3.0
click             8.0.4

Every time I try to commit, I get:

```
black....................................................................Failed
- hook id: black
- exit code: 1
Traceback (most recent call last):
  File "/home/isaac/.cache/pre-commit/repojq0me61h/py_env-python3.8/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/isaac/.cache/pre-commit/repojq0me61h/py_env-python3.8/lib/python3.8/site-packages/black/__init__.py", line 1423, in patched_main
    patch_click()
  File "/home/isaac/.cache/pre-commit/repojq0me61h/py_env-python3.8/lib/python3.8/site-packages/black/__init__.py", line 1409, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/home/isaac/.cache/pre-commit/repojq0me61h/py_env-python3.8/lib/python3.8/site-packages/click/__init__.py)
```

**Comment by JelleZijlstra** [comment]
@iboates you have an outdated version of Black in your pre-commit environment. See this comment for a possible solution: https://github.com/psf/black/issues/2964#issuecomment-1083591334

**Comment by alexcoca** [comment]
> > This still does not work for me. Any idea why? I am still getting the error despite pinning the version.
> 
> Can you provide any additional information? Is the error coming from a pre-commit hook? Virtual environment, etc.

Yes, the error was coming from a pre-commit hook. I updated to current `black` master and then updated click to `8.1.1` and that did the trick.
